"""
heygen_video.py — CSK Content Engine

Generates AI avatar videos using the HeyGen CLI (v3 API).
Daily clips: Video Agent Essential mode (60s, unlimited, no premium credits).
Weekly hero: multi-scene manifest mode (2-3 min, Sora/Veo b-roll).
"""

import os
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from utils.logger import get_logger

logger = get_logger("heygen_video")


# ---------------------------------------------------------------------------
# Avatar discovery
# ---------------------------------------------------------------------------

def get_correct_avatar_id() -> list[dict]:
    """
    Runs `heygen avatar list` and returns the available avatars as a list.
    Use this to find the correct HEYGEN_AVATAR_ID for your .env.
    """
    result = subprocess.run(
        ["heygen", "avatar", "list"],
        capture_output=True, text=True, timeout=30,
    )
    if result.returncode != 0:
        raise RuntimeError(f"heygen avatar list failed: {result.stderr}")
    try:
        avatars = json.loads(result.stdout)
        logger.info(f"Available avatars: {[a.get('avatar_id') for a in avatars]}")
        return avatars
    except Exception:
        logger.info(f"Avatar list output:\n{result.stdout}")
        return []


# ---------------------------------------------------------------------------
# Daily short clip (Video Agent Essential — 60 seconds)
# ---------------------------------------------------------------------------

def generate_daily_video(script: str, output_path: str) -> dict:
    """
    Generates a 60-second daily clip via HeyGen Video Agent Essential mode.
    B-roll is selected automatically — no premium credits consumed.
    Returns the CLI response dict.
    Raises RuntimeError on failure.
    """
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    logger.info(f"Generating daily video via HeyGen CLI → {output_path}")

    result = subprocess.run(
        [
            "heygen", "video-agent", "create",
            "--avatar-id", os.environ["HEYGEN_AVATAR_ID"],
            "--voice-id",  os.environ["HEYGEN_VOICE_ID"],
            "--prompt",    script,
            "--mode",      "essential",
            "--output",    output_path,
        ],
        capture_output=True, text=True, timeout=600,
    )
    if result.returncode != 0:
        raise RuntimeError(f"HeyGen CLI daily video failed: {result.stderr}")

    try:
        data = json.loads(result.stdout)
    except Exception:
        data = {"output_path": output_path, "raw": result.stdout}

    logger.info(f"Daily video generated: {output_path}")
    return data


# ---------------------------------------------------------------------------
# Weekly hero video (multi-scene manifest — 2-3 minutes)
# ---------------------------------------------------------------------------

def generate_weekly_video(manifest_path: str, output_path: str) -> dict:
    """
    Generates a 2-3 minute weekly hero video from a scene manifest JSON.
    Uses Sora/Veo for b-roll (premium credits). Manifest is generated by
    content_creator.generate_scene_manifest().
    Returns the CLI response dict.
    Raises RuntimeError on failure.
    """
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    logger.info(f"Generating weekly video from manifest {manifest_path} → {output_path}")

    result = subprocess.run(
        [
            "heygen", "video", "create-from-manifest",
            "--manifest",  manifest_path,
            "--avatar-id", os.environ["HEYGEN_AVATAR_ID"],
            "--voice-id",  os.environ["HEYGEN_VOICE_ID"],
            "--output",    output_path,
        ],
        capture_output=True, text=True, timeout=900,
    )
    if result.returncode != 0:
        raise RuntimeError(f"HeyGen CLI weekly video failed: {result.stderr}")

    try:
        data = json.loads(result.stdout)
    except Exception:
        data = {"output_path": output_path, "raw": result.stdout}

    logger.info(f"Weekly video generated: {output_path}")
    return data


# ---------------------------------------------------------------------------
# Full daily pipeline entry point (called from main_daily.py)
# ---------------------------------------------------------------------------

def create_avatar_video(idea: dict, date_str: str, video_script: str) -> dict | None:
    """
    Full pipeline for one daily video: generate via HeyGen CLI → save metadata.
    Takes the pre-written video_script from content_creator (avoid duplicate generation).
    Saves to content/{date}/track3/. Returns metadata dict or None on failure.
    """
    score = idea.get("scores", {}).get("total", 0)
    title = idea.get("title", "CSK Tech Video")[:80]
    out_dir = Path(f"content/{date_str}/track3")
    out_dir.mkdir(parents=True, exist_ok=True)

    slug = title.lower().replace(" ", "_")[:40]
    output_path = str(out_dir / f"daily_{slug}.mp4")

    try:
        logger.info(f"=== HeyGen daily pipeline: {title} ===")
        result = generate_daily_video(video_script, output_path)

        meta = {
            "title":          title,
            "script":         video_script,
            "raw_video_path": output_path,
            "idea_score":     score,
            "status":         "rendered",
            "created_at":     datetime.now(timezone.utc).isoformat(),
        }
        meta_path = out_dir / f"video_meta_{slug}.json"
        with open(meta_path, "w") as f:
            json.dump(meta, f, indent=2)
        logger.info(f"=== HeyGen daily pipeline complete: {output_path} ===")
        return meta

    except Exception as e:
        logger.error(f"HeyGen daily pipeline failed for '{title}': {e}")
        return None


if __name__ == "__main__":
    print("Available avatars:")
    try:
        avatars = get_correct_avatar_id()
        for a in avatars:
            print(f"  {a.get('avatar_id')} — {a.get('name', '')}")
    except Exception as e:
        print(f"Error: {e}")
        print("Make sure HeyGen CLI is installed: npm install -g @heygen/cli")
